import React from 'react';
import '../../App.css';

function TheGreatCrusade() {
  return (
    <div className='TheGreatCrusade'>
          <h1>The Great Crusade</h1><br/>
      <div id="scroll-container">
      The Great Crusade of the Emperor of Mankind began as the Age of Strife came to an end for humanity. The Warp Storms isolating the human colony worlds for 5,000 Terran years had finally disappeared with the birth of Slaanesh and the Fall of the Eldar in the 30th Millennium, and the Emperor of Mankind, who had united Terra under his rule during the Unification Wars at the end of the Age of Strife, was ready with his genetically-enhanced Space Marines and the Imperial Army to reunite all of humanity under his enlightened rule and the rationalist philosophy of Imperial Truth. Making a pact known as the Treaty of Mars with the Cult Mechanicus of the Machine God on Mars in the late 30th Millennium the Emperor promised to spare their lives (the Emperor despised their use of bionics and rigid adherence to organized religion as being against everything that he stood for) so long as they aided him in his mission to reunite humanity across the galaxy. The Emperor was a man of enormous skill in the practice of science and the development of new technology, and so in him many members of the Cult of the Machine saw the coming of the Omnissiah that had been prophesied by their faith. In the treaty they signed with the Emperor, the Mechanicum of Mars pledged their support to the creation of a new Imperium of Man in which they would serve as the Adeptus Mechanicus, and the symbol of the Imperium changed from the lightning bolt used by the Emperor during the Unification Wars on Terra to the double-headed eagle known as the Aquila, to symbolise the union of the empires of Earth and Mars. With the forge factories and industrial output of Mars, the Emperor was able to refit his armies, and more importantly, he now had the use of the Adeptus Mechanicus' Titan Legions, giant robotic war machines with the potential to dominate the battlefield.<br/><br/>
      At first, the Imperium's expansion into interstellar space was slow, since the Imperial Army was still small, and more importantly the Emperor's 20 Space Marine Legions were inhibited by the absence of their Primarchs, which made the enhancement time for the creation of a new Space Marine much longer. However, this was to end, as on Cthonia, a planet in a star system not far from Terra, the Emperor for the first time was reunited with one of his missing Primarchs, Horus. Having been discovered at an early age, the Emperor took Horus under his wing and taught him all he knew. Horus and the Emperor had a truly unique bond, that of father and son, and many times they saved each others' lives. But after 30 years, the Emperor discovered another of the Space Marine Primarchs, Roboute Guilliman. Although Horus was pleased at the discovery of one of his brothers, he secretly hoped to always be the Emperor's favorite son.<br/><br/>
      In time, all the Primarchs were found on the worlds they had been sent to by the machinations of the Ruinous Powers of Chaos, and each was placed in command of their respective Space Marine Legions. The Legions as a result were massively expanded with new recruits from their Primarch's adopted homeworlds, and new Space Marines could now be produced within only a single Terran year. But this acceleration produced fundamental defects within the psyche of each Space Marine which was later to prove fatal to many.<br/><br/>
      The Great Crusade lasted for 200 standard years, into the early years of the 31st Millennium, and brought many long lost star systems into the fold of the newborn Imperium of Man. Under the command of the War Council of the Emperor and his rediscovered Primarchs, vast Expeditionary Fleets comprised of the Imperial Army and the twenty Space Marine Legions fought back aliens, feral human tribes, petty human dictators and the Warp-tainted forces that had gained control of large portions of human-settled space during the Age of Strife. Once a human-settled world had been pacified, it was brought into "Imperial Compliance" by a new Imperial Planetary Governor chosen by the Emperor. Part of this process included the rooting out of any superstitious or religious beliefs of the population with a respect solely for reason and the measured advancement of science and technology, an atheistic belief system known as the Imperial Truth. It was often occupied by a unit or units of the Imperial Army that were left behind to complete the integration of the planet into the Imperium while the Expeditionary Fleet, led by Astartes, moved on to its next target. As the Primarchs took control of the Space Marine Legions that had been crafted from their gene-seed, the Great Crusade separated, moving in many directions and reaching far across the galaxy.<br/><br/>
      After the Imperial Crusade on the world of Ullanor concluded upon bringing that planet into "Imperial Compliance," the Emperor claimed it as the greatest victory of the Imperium to date, and that Horus should be given all credit. Hailing Horus and his Luna Wolves Legion (later renamed the Sons of Horus), the Emperor stated that he would have to leave the expeditionary fleets behind and return to Terra to begin the next, secret phase of his plan to ensure humanity's domination of the galaxy, and that in his place Horus would be declared Warmaster, the de facto commander of all the Emperor's armies on the Great Crusade. Although Horus was troubled that the Emperor should leave him and his brother Primarchs to carry on alone for some unknown reason, with Horus as their new commander, the Imperium's armies and Space Marines continued to expand ever outwards, rediscovering lost human worlds and bringing them into the enlightened Imperium's fold. This situation lasted until the outbreak of the terrible Horus Heresy.
      </div>
    </div>
  );
}

export default TheGreatCrusade;